from setuptools import setup, find_packages

setup(
    name='behemot_framework',
    version='0.2.3',
    packages=find_packages(),
    install_requires=[
        # Dependencias del framework (copiar de requirements.txt)
        'fastapi',
        'uvicorn',
        'requests',
        'python-dotenv',
        'openai',
        'redis',
        'gdown',
        'pandas',
        'sentence-transformers',
        'langchain>=0.1.0',
        'langchain-openai>=0.0.5',
        'langchain-community>=0.0.13',
        'pypdf>=3.17.1',
        'faiss-cpu>=1.7.4',
        'tiktoken>=0.5.1',
        'chromadb>=0.4.22',
        'langchain-chroma>=0.1.0',
        'google-cloud-storage>=2.9.0',
        'google-api-python-client',
        'boto3',
        'google-auth==2.28.1',
        'unstructured>=0.4.16',
        'markdown',
        'python-multipart',
        'python-telegram-bot',
        'twilio',
        'pydub',
        'ffmpeg-python',
        'SpeechRecognition',
        'openai-whisper',
        'soundfile',
        'faster-whisper',
        'deepgram-sdk',
        'pytest',
        'pytest-asyncio',
        'respx',
        'httpx',
        'google-generativeai>=0.3.0',
        'langchain-google-genai>=1.0.0',
        'gradio>=4.0.0',
        'Pillow>=10.0.0',
    ],
    author='Your Name', # Reemplazar con tu nombre
    author_email='your.email@example.com', # Reemplazar con tu email
    description='A modular framework for building multimodal AI assistants.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/behemot_framework', # Reemplazar con la URL de tu repositorio
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
    ],
    python_requires='>=3.9',
    entry_points={
        'console_scripts': [
            'behemot-admin=behemot_framework.cli.admin:main',
        ],
    },
)
